# Generated by Django 5.0.2 on 2024-02-25 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='register_date',
        ),
    ]
